In [13]:
pip install pandas scikit-learn notebook ipykernel

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: scikit-learn in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: notebook in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (7.5.6)
Requirement already satisfied: ipykernel in c:\users\asus\appdata\roaming\python\python313\site-packages (7.2.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from notebook) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from notebook) (2.28.0)
Requirement already satisfied: jupyterlab<4.6,>=4.5.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from notebook) (4.5.7)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from notebook) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from notebook) (6.5.5)
Requirement already satisfied: comm>=0.1.1 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (26.2)
Requirement already satisfied: psutil>=5.7 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.6)
Requirement already satisfied: anyio>=3.1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (4.13.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (3.1.6)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (7.17.1)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.25.0)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (3.0.3)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook) (1.9.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (0.28.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (2.3.1)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab<4.6,>=4.5.7->notebook) (82.0.1)
Requirement already satisfied: babel>=2.10 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (4.26.0)
Requirement already satisfied: requests>=2.31 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.33.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: idna>=2.8 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook) (3.13)
Requirement already satisfied: argon2-cffi-bindings in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (25.1.0)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.7->notebook) (0.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\asus\appdata\roaming\python\python313\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (0.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (6.3.0)
Requirement already satisfied: defusedxml in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (3.2.1)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook) (2.21.2)
Requirement already satisfied: wcwidth in c:\users\asus\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (2.6.3)
Requirement already satisfied: executing>=1.2.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\asus\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\asus\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Requirement already satisfied: webencodings in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (1.4.0)
Requirement already satisfied: fqdn in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.5.1)
Requirement already satisfied: isoduration in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.1.0)
Requirement already satisfied: uri-template in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (25.10.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (2.0.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook) (4.15.0)
Requirement already satisfied: pycparser in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook) (3.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->notebook) (1.4.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
import re
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

Load data

In [15]:
df = pd.read_csv("../data/processed/merged_dataset.csv")

print(df.columns)
df.head()

Index(['name', 'category', 'rating', 'address', 'type'], dtype='str')

,name,category,rating,address,type
0,Taman Budaya Yogyakarta,pusat kebudayaan,4.6,"Jl. Sriwedani No.1, Ngupasan, Kec. Gondomanan,...",wisata
1,Vredeburg Fort Museum,museums,4.7,"Jl. Margo Mulyo No.6, Ngupasan, Kec. Gondomana...",wisata
2,Situs Pesanggrahan Rejawinangun,attractions,4.4,"Jl. Veteran No.77, Warungboto, Kec. Umbulharjo...",wisata
3,Taman Sari Tourist Village,attractions,4.6,"Patehan, Kraton, Yogyakarta City, Special Regi...",wisata
4,Bentara Budaya Yogyakarta (BBY),attractions,4.6,"Jl. Suroto No.2, Kotabaru, Kec. Gondokusuman, ...",wisata

In [16]:
# OPTIONAL
if "subtypes" in df.columns:
    df["subtypes"] = df["subtypes"].fillna("")
else:
    df["subtypes"] = ""

In [17]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)  # hapus simbol
    text = re.sub(r'\s+', ' ', text).strip()     # hapus spasi berlebih
    return text

In [18]:
def clean_subtypes(text):
    text = str(text).lower()
    
    # buang kata terlalu umum
    remove_words = ["attractions", "place", "point", "location"]
    
    words = text.split()
    words = [w for w in words if w not in remove_words]
    
    return " ".join(words)

df["subtypes_clean"] = df["subtypes"].apply(clean_subtypes)

df[["subtypes", "subtypes_clean"]].head()

  subtypes subtypes_clean
0
1
2
3
4

In [19]:
df["text"] = (
    df["name"].fillna("") + " " +
    df["category"].fillna("") + " " +
    df["type"].fillna("") + " " +
    df["subtypes"].fillna("")
)

df["text"] = df["text"].apply(clean_text)

df[["name", "text"]].head()

,name,text
0,Taman Budaya Yogyakarta,taman budaya yogyakarta pusat kebudayaan wisata
1,Vredeburg Fort Museum,vredeburg fort museum museums wisata
2,Situs Pesanggrahan Rejawinangun,situs pesanggrahan rejawinangun attractions wi...
3,Taman Sari Tourist Village,taman sari tourist village attractions wisata
4,Bentara Budaya Yogyakarta (BBY),bentara budaya yogyakarta bby attractions wisata

TF-IDF

In [20]:
vectorizer = TfidfVectorizer(
    stop_words="english",   # buang kata ga penting
    ngram_range=(1,2),      # tangkap "hotel murah"
    min_df=2                # buang kata terlalu jarang (noise)
)

tfidf_matrix = vectorizer.fit_transform(df["text"])

print("TF-IDF shape:", tfidf_matrix.shape)

TF-IDF shape: (726, 469)

SAVE MODEL

In [21]:
with open("../data/processed/tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

with open("../data/processed/tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)

print("TF-IDF saved ✅")

TF-IDF saved ✅

In [22]:
# CEK SHAPE
print("Shape:", tfidf_matrix.shape)

# CEK ISI MATRIX (baris pertama)
print(tfidf_matrix[0].toarray())

# CEK FEATURE (kata yang dipelajari model)
print(vectorizer.get_feature_names_out()[:20])

Shape: (726, 469)
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.43016893 0.46691811
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.44622205 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.33801758 0.46691811 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.15793147 0.         0.         0.         0.
  0.20153733 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]]
['1o1' 'adventure' 'adventure attractions' 'agen' 'air' 'air terjun'
 'alam' 'alam wisata' 'ambarrukmo' 'ambarrukmo yogyakarta' 'angkringan'
 'arah' 'area' 'area rekreasi' 'arum' 'asih' 'asli' 'asri' 'attractions'
 'attractions hotel']

In [23]:
feature_names = vectorizer.get_feature_names_out()

print(feature_names[:20])

['1o1' 'adventure' 'adventure attractions' 'agen' 'air' 'air terjun'
 'alam' 'alam wisata' 'ambarrukmo' 'ambarrukmo yogyakarta' 'angkringan'
 'arah' 'area' 'area rekreasi' 'arum' 'asih' 'asli' 'asri' 'attractions'
 'attractions hotel']