Import

In [38]:
import pandas as pd
import pickle
from sklearn.metrics.pairwise import cosine_similarity

Load Dataset

In [39]:
df = pd.read_csv("../data/processed/merged_dataset.csv")

df.head()

,name,category,rating,address,type
0,Taman Budaya Yogyakarta,pusat kebudayaan,4.6,"Jl. Sriwedani No.1, Ngupasan, Kec. Gondomanan,...",wisata
1,Vredeburg Fort Museum,museums,4.7,"Jl. Margo Mulyo No.6, Ngupasan, Kec. Gondomana...",wisata
2,Situs Pesanggrahan Rejawinangun,attractions,4.4,"Jl. Veteran No.77, Warungboto, Kec. Umbulharjo...",wisata
3,Taman Sari Tourist Village,attractions,4.6,"Patehan, Kraton, Yogyakarta City, Special Regi...",wisata
4,Bentara Budaya Yogyakarta (BBY),attractions,4.6,"Jl. Suroto No.2, Kotabaru, Kec. Gondokusuman, ...",wisata

Load TF-IDF MODEL

In [40]:
with open("../data/processed/tfidf_vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)

with open("../data/processed/tfidf_matrix.pkl", "rb") as f:
    tfidf_matrix = pickle.load(f)

print("Model loaded ✅")

Model loaded ✅

CEK DIMENSI

In [41]:
print("Data:", df.shape)
print("TF-IDF:", tfidf_matrix.shape)

Data: (726, 5)
TF-IDF: (726, 469)

FUNCTION RECOMMEND

In [42]:
def recommend_places(query, df, vectorizer, tfidf_matrix, top_n=5, filter_type=None):
    query_vec = vectorizer.transform([query])
    sim_scores = cosine_similarity(query_vec, tfidf_matrix).flatten()
    
    top_indices = sim_scores.argsort()[::-1]
    
    results = df.iloc[top_indices].copy()
    
    # 🔥 FILTER TYPE
    if filter_type:
        results = results[results["type"] == filter_type]
    
    return results[["name", "category", "rating", "type"]].head(top_n)

TEST 1

In [43]:
recommend_places("pantai", df, vectorizer, tfidf_matrix, filter_type="wisata")

                       name          category  rating    type
23          Pantai Nguyahan       attractions     4.6  wisata
22             Pantai Drini       attractions     4.6  wisata
24              Pantai baru       attractions     4.6  wisata
16           Gereja Sayidan       attractions     4.3  wisata
0   Taman Budaya Yogyakarta  pusat kebudayaan     4.6  wisata

TEST 2

In [44]:
recommend_places("cafe", df, vectorizer, tfidf_matrix)

                   name     category  rating     type
363      Rame Rame Cafe  restaurants     4.0  kuliner
352            Cafe AMC        cafes     4.0  kuliner
299          Cafe Bunga        cafes     4.3  kuliner
282  CAFE MACAN OM GABS        cafes     5.0  kuliner
359        cafe for you        cafes     2.5  kuliner

TEST 3

In [45]:
recommend_places("hotel murah", df, vectorizer, tfidf_matrix, filter_type="hotel")

,name,category,rating,type
709,Faire BNB Homestay | Penginapan Murah Jogja | ...,hotels,4.9,hotel
581,Hotel Talenta 3,losmen,4.2,hotel
719,PULANG ke UTTARA,akomodasi berlayanan,4.7,hotel
583,Hotel Cristalit,hotels,3.9,hotel
512,Hotel Kalingga,hotels,3.9,hotel

TEST 4 REAL

In [46]:
recommend_places("wisata budaya", df, vectorizer, tfidf_matrix)

                                name          category  rating    type
4    Bentara Budaya Yogyakarta (BBY)       attractions     4.6  wisata
213  Tembi Desa Budaya ꦠꦼꦩ꧀ꦧꦶꦢꦼꦱꦧꦸꦢꦪ           museums     4.5  wisata
15            Taman Budaya ꧋ꦠꦩꦤ꧀ꦧꦸꦣꦪ       attractions     4.7  wisata
0            Taman Budaya Yogyakarta  pusat kebudayaan     4.6  wisata
80                   Wisata Kalibiru       attractions     4.4  wisata